In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [16]:
# lista = []

# resposta_pergunta = int(input('Digite a quantidade de vendas no ano: '))

# for i in range(0, resposta_pergunta):
#     valor = float(input('Digite o valor da venda: '))
#     lista.append(valor)

# lista = np.array(lista)
# lista

In [ ]:
# diametro_laranja = dado[:5000,0]
# diametro_toranja = dado[5000:,0]
# peso_laranja = dado[:5000,1]
# peso_toranja = dado[5000:,1]

NameError: name 'dado' is not defined

In [ ]:
# plt.plot(diametro_laranja, peso_laranja)
# plt.plot(diametro_toranja, peso_toranja)

Atividade 1 -

In [17]:
caminho_url = 'https://raw.githubusercontent.com/allanspadini/numpy/dados/citrus.csv'
cols = np.arange(1, 6, 1)

dado = np.loadtxt(caminho_url, delimiter=',', usecols=cols, skiprows=1)

In [18]:
dado

array([[  2.96,  86.76, 172.  ,  85.  ,   2.  ],
       [  3.91,  88.05, 166.  ,  78.  ,   3.  ],
       [  4.42,  95.17, 156.  ,  81.  ,   2.  ],
       ...,
       [ 15.59, 256.5 , 168.  ,  82.  ,  20.  ],
       [ 15.92, 260.14, 142.  ,  72.  ,  11.  ],
       [ 16.45, 261.51, 152.  ,  74.  ,   2.  ]], shape=(10000, 5))

Atividade 2 -

In [24]:
dados_transpostos = dado.T

In [48]:
dados = dados_transpostos

In [ ]:
diametro_laranja = dados[0,:5000]
diametro_toranja = dados[0,5000:]
peso_laranja = dados[1,:5000]
peso_toranja = dados[1,5000:]

In [51]:
diametro_laranja

array([ 2.96,  3.91,  4.42, ..., 12.28, 12.55, 12.75], shape=(4999,))

In [55]:
diametro_laranja.shape

(4999,)

Atividade 3 - 

In [65]:
Y = peso_toranja
X = diametro_toranja
n = np.size(X)

a = (n*sum(X*Y) - sum(X)*sum(Y)) / (n*sum(np.power(X,2)) - (sum(X))**2)
b = np.mean(Y) - a * np.mean(X)

Atividade 4 -

In [73]:
b=17

In [76]:
np.random.seed(84)
coef_angulares = np.random.uniform(0, 30.0, 100)

norma = np.array([])
for i in range(100):
    
    norma = np.append(norma, np.linalg.norm(Y - (coef_angulares[i]*X+b)))

In [77]:
norma

array([11693.67355856,  3756.21335179,  6888.14382259,  2567.04685515,
       11420.77932891,  9623.66917996,  8570.85655292,  6496.51679273,
        2577.28271294,  9613.12064833,  5709.72883857,   695.35964734,
       10855.07029288,  5539.82389583,  3137.98293399,   296.30778902,
        8896.93668493,  8347.82090288, 10206.95670568, 10229.7542583 ,
        2193.54863897,  8448.39951623, 11004.80458021, 11563.3388543 ,
        4098.18752189,  7732.70842098,  2801.84736004,  7688.60780777,
       11134.73586307,  9432.12778879,   725.4664674 ,  6290.36141277,
        5189.67184491,  4716.99608173,  9250.47142251,  7274.49676931,
        8876.20611799,   621.16747277,  4716.1854569 ,  8050.51001798,
        9238.31227388,  3992.98429323, 11531.1764187 ,  5849.11139809,
        1042.57303406,  9875.3710071 , 11759.24152592,  8956.15615033,
        2219.50808351,  3585.49846047, 11347.59016791,  2477.87811921,
         878.91891293,  2740.88025627,  1766.171738  ,   710.47076735,
      

In [78]:
np.min(norma)

np.float64(104.40529157196431)

In [79]:
coef_angulares[norma == np.min(norma)]

array([15.82512199])